#!/bin/sh
set -e

if [ $# -eq 0 ]
then
    srcs="."
else
    srcs="$@"
fi

ignore_chunk_descriptions() {
  grep -v "^!.*!$"
}

ignore_chunk_separators() {
  grep -v "^\"--.*\"!$"
}

ignore_comments() {
  sed 's/".*"//g'
}

find $srcs -name '*.st' -execdir cat {} \; -printf '\n' | ignore_chunk_descriptions | ignore_chunk_separators | ignore_comments