#!/bin/sh
set -e

if [ $# -eq 0 ]
then
    srcs="."
else
    srcs="$@"
fi

ignore_chunk_descriptions() {
  grep -v "^!.*!$"
}

ignore_chunk_separators() {
  grep -v "^\"--.*\"!$"
}

find $srcs -name '*.st' -exec cat {} \; | ignore_chunk_descriptions | ignore_chunk_separators