#!/bin/sh

set -e
basedir=`dirname $0`
jarfile=$basedir/wordcram-cli/lib/wordcram-cli.jar

if [ ! -e $jarfile ]
then
	echo "ERROR: $jarfile does not exist (run make to build it)" 1>&2
	exit 1
fi

java -jar $jarfile "$@"

